[tool.poetry]
name = "social-insecurity"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "7.0"
dominate = "2.4.0"
Flask = "1.1.1"
Flask-Bootstrap = "3.3.7.1"
Flask-WTF = "0.14.2"
itsdangerous = "1.1.0"
Jinja2 = "2.10.1"
MarkupSafe = "1.1.1"
visitor = "0.1.3"
Werkzeug = "0.15.6"
wincertstore = "0.2"
WTForms = "2.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
