[tool.poetry]
name = "social-insecurity"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
Flask-WTF = "^1.0.1"
python = "^3.10"
click = "^8.1.3"
dominate = "^2.7.0"
Flask = "^2.2.2"
Flask-Bootstrap = "^3.3.7"
itsdangerous = "^2.1.2"
Jinja2 = "^3.1.2"
MarkupSafe = "^2.1.1"
visitor = "^0.1.3"
Werkzeug = "^2.2.2"
wincertstore = "0.2"
WTForms = "^3.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
